### ISSUE TITLE
Framework is not compiling

### ISSUE THREAD

**Issue by superhard** [onmyway133/Anchors#1]
There is an error "Argument labels '(rawValue:)' do not match any available overloads" on 17 line in Anchor+Constraints.swift file.
It works if i modify file manually, but it is not the case, hope you will fix it. 
It is quite sad that there is no contributors here.

**Comment by onmyway133** [comment]
@superhard Hi, glad that you like `Anchors`. Do you use https://github.com/onmyway133/Anchors/releases/tag/2.2.1 and set `.swift-version` to 4.0 ?

**Comment by superhard** [comment]
@onmyway133 Thanks for reply, the issue was wrong swift version in pod target.
Do you plan to support and develop this library in the future? It feels interesting to use it as main layout framework in project but a little scary. 
P.S Ability to find existing constraints on view is killer feature! This is what i really miss in other frameworks.

**Comment by onmyway133** [comment]
@superhard I use this in all my projects. If you take a look at my code, it is a lot simpler and reasonable than in SnapKit

**Comment by onmyway133** [comment]
@superhard I will close this issue for now. Feel free to open new issues if you have any questions ❤️
