### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by zdnk** [onmyway133/Anchors#3]
Any plans to support Swift Package Manager anytime soon?

**Comment by onmyway133** [comment]
@zdnk Hi, I will try to add SPM for all my pods. Glad that you find Anchors useful.

**Comment by onmyway133** [comment]
@zdnk Hi, I just added support for SPM, can you check https://github.com/onmyway133/Anchors/releases/tag/2.5.2 ?

**Comment by zdnk** [comment]
seems like it working ok! 👍

**Comment by onmyway133** [comment]
@zdnk ja, I use Anchors in all of my projects, even on macOS, and it works 😎

**Comment by zdnk** [comment]
Hey, when you renamed the project, you broke SPM integration, could you please look at it and dix it please? :)

**Comment by onmyway133** [comment]
@zdnk Sorry for this convenience, can you point SPM package in Xcode to this new release https://github.com/onmyway133/EasyAnchor/releases/tag/3.0.0 ?

**Comment by zdnk** [comment]
The issue is that that version does not work with SPM, I have to point to <3.0.0 where the Paackage.swift is up-to-date with the naming and folder structure. You need to update your folder strucuture in 3.0.0 so it is compatible with SPM.

**Comment by onmyway133** [comment]
@zdnk Hi, what should I update https://github.com/onmyway133/EasyAnchor/blob/3.0.0/Package.swift ?
