### ISSUE TITLE
Make better algorithm to find constraints

### ISSUE THREAD

**Issue by o-nnerb** [onmyway133/Anchors#4]
When using the find method, EasyAnchor should lookup for constraints that are equal to the properties inside Anchor.

For example, I have set the anchor edges; width equal to height. To find the top constraint, I count use something like that `anchor.top.find`. In a scenario that there are a lot of constraints related to  top, I could specify more attributes to find it like `anchor.top.priority(750).constant(10)`

**Comment by onmyway133** [comment]
@brennobemoura Hi, good point, would you like to make a PR? Another way is to just get a list of constraints from the view and filter

**Comment by o-nnerb** [comment]
I have already implemented, now I am testing

**Comment by o-nnerb** [comment]
See PR #5
