### ISSUE TITLE
I have one Question..

### ISSUE THREAD

**Issue by lohenyumnam** [onmyway133/Anchors#6]
I am a big fan of programmatically UI, and so far I am doing everything manually using apple's own API, but it takes a lot of time and I was looking around and found several options. I find your EasyAnchor really clean and short. 

So, My Question is simple, how long you are playing to support this project? I would love to use EasyAnchor on my future project.

**Comment by onmyway133** [comment]
@lohenyumnam, Hi I will continue to support this until no one use Auto Layout any more. I use this for all of my apps and certain apps at my company are using this too

**Comment by lohenyumnam** [comment]
> @lohenyumnam, Hi I will continue to support this until no one use Auto Layout any more. I use this for all of my apps and certain apps at my company are using this too

Thank you for your reply. 
If that's the plan I will use this library on my future project, and I will recommend it to my team too. 

This project is amazing.
